//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelISP9_13.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            this.HotelRoom = new HashSet<HotelRoom>();
        }
    
        public int IdHotel { get; set; }
        public string HotelName { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public int Stars { get; set; }
        public string Phone { get; set; }
        public string Description { get; set; }
        public byte[] MainPhoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelRoom> HotelRoom { get; set; }
    }
}
