//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelISP9_13.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentRoom
    {
        public int IdClient { get; set; }
        public int IdRoom { get; set; }
        public string DateRent { get; set; }
        public int RentalPeriod { get; set; }
        public Nullable<int> IdEmployee { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual HotelRoom HotelRoom { get; set; }
    }
}
